#!/usr/bin/env bash

APP="alisinabh" # name of your release

BUILD_HOST="alisinabh.com" # host where to build the release
BUILD_USER="root" # local user at build host
BUILD_AT="/git/alisinabh.com/builds" # build directory on build host
RELEASE_DIR="/git/alisinabh.com/builds/rel/alisinabh"
RELEASE_VERSION=0.0.1

STAGING_HOSTS="alisinabh.com" # staging / test hosts separated by space
STAGING_USER="root" # local user at staging hosts
TEST_AT="/test/alisinabh.com" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="alisinabh.com" # deploy / production hosts separated by space
PRODUCTION_USER="root" # local user at deploy hosts
DELIVER_TO="/opt/alisinabh.com" # deploy directory on production hosts
